# frozen_string_literal: true

require "fileutils"
require "tmpdir"

module SaferAgent
  class DockerManager
    SENSITIVE_FILES = [
      ".env",
      ".env.*",
      "*.pem",
      "*.key",
      "*.p12",
      "*.pfx",
      "*.crt",
      "id_rsa*",
      "*.secret",
      "secrets.yml",
      "credentials.yml",
      "*.credentials",
      ".aws/credentials",
      ".ssh/id_*",
      "*.kdbx"
    ].freeze

    AGENT_SETTINGS_DIRS = [
      ".claude",
      ".cursor",
      ".copilot",
      ".aider",
      ".continue"
    ].freeze

    AGENT_VOLUME_MOUNT = "/root/.agent-settings"

    attr_reader :working_dir, :container_name, :volume_name

    def initialize(working_dir: Dir.pwd)
      @working_dir = File.expand_path(working_dir)
      @container_name = "safer-agent-#{Time.now.to_i}-#{rand(1000)}"
      @volume_name = "safer-agent-settings"
    end

    def create_dockerignore
      dockerignore_path = File.join(working_dir, ".dockerignore")
      
      # Don't overwrite existing .dockerignore
      return if File.exist?(dockerignore_path)

      File.write(dockerignore_path, generate_dockerignore_content)
      puts "Created .dockerignore at #{dockerignore_path}"
      dockerignore_path
    end

    def generate_dockerignore_content
      content = "# Generated by safer-agent\n"
      content += "# Sensitive files to exclude from Docker context\n\n"
      
      SENSITIVE_FILES.each do |pattern|
        content += "#{pattern}\n"
      end
      
      content += "\n# Build artifacts and dependencies\n"
      content += "node_modules/\n"
      content += "vendor/\n"
      content += "*.log\n"
      content += ".git/\n"
      
      content
    end

    def ensure_volume_exists
      # Check if volume exists
      volume_list = `docker volume ls --format '{{.Name}}'`.split("\n")
      
      if !volume_list.include?(volume_name)
        puts "Creating named volume: #{volume_name}"
        system("docker", "volume", "create", volume_name) || raise("Failed to create volume")
      else
        puts "Using existing volume: #{volume_name}"
      end
    end

    def run_container(image: "ubuntu:latest", command: "/bin/bash", interactive: true)
      create_dockerignore
      ensure_volume_exists
      
      docker_args = ["docker", "run"]
      docker_args << "--rm"
      docker_args << "-it" if interactive
      docker_args << "--name"
      docker_args << container_name
      docker_args << "-v"
      docker_args << "#{working_dir}:/workspace"
      docker_args << "-w"
      docker_args << "/workspace"
      
      # Check if any agent settings directories exist in the working directory
      has_agent_dirs = AGENT_SETTINGS_DIRS.any? { |dir| File.directory?(File.join(working_dir, dir)) }
      
      if has_agent_dirs
        # Mount the named volume for persistent agent settings
        docker_args << "-v"
        docker_args << "#{volume_name}:#{AGENT_VOLUME_MOUNT}"
      end
      
      docker_args << image
      
      # Split command if it's a complex command
      if command.include?(" ")
        docker_args << "/bin/sh"
        docker_args << "-c"
        docker_args << command
      else
        docker_args << command
      end
      
      puts "Running: #{docker_args.join(' ')}"
      
      exec(*docker_args)
    end

    def cleanup
      puts "Cleaning up container: #{container_name}"
      system("docker", "stop", container_name, err: File::NULL)
      system("docker", "rm", container_name, err: File::NULL)
    end
  end
end
