# frozen_string_literal: true

require "fileutils"
require "tmpdir"

module SaferAgent
  class DockerManager
    SENSITIVE_FILES = [
      ".env",
      ".env.*",
      "*.pem",
      "*.key",
      "*.p12",
      "*.pfx",
      "*.crt",
      "id_rsa*",
      "*.secret",
      "secrets.yml",
      "credentials.yml",
      "*.credentials",
      ".aws/credentials",
      ".ssh/id_*",
      "*.kdbx"
    ].freeze

    AGENT_SETTINGS_DIRS = [
      ".claude",
      ".cursor",
      ".copilot",
      ".aider",
      ".continue"
    ].freeze

    AGENT_VOLUME_MOUNT = "/root/.agent-settings"
    CUSTOM_IMAGE_NAME = "safer-agent-custom"

    attr_reader :working_dir, :container_name, :volume_name, :config

    def initialize(working_dir: Dir.pwd, config: nil)
      @working_dir = File.expand_path(working_dir)
      @container_name = "safer-agent-#{Time.now.to_i}-#{rand(1000)}"
      @volume_name = "safer-agent-settings"
      @config = config || Config.new
    end

    def create_dockerignore
      dockerignore_path = File.join(working_dir, ".dockerignore")
      
      # Don't overwrite existing .dockerignore
      return if File.exist?(dockerignore_path)

      File.write(dockerignore_path, generate_dockerignore_content)
      puts "Created .dockerignore at #{dockerignore_path}"
      dockerignore_path
    end

    def generate_dockerignore_content
      content = "# Generated by safer-agent\n"
      content += "# Sensitive files to exclude from Docker context\n\n"
      
      SENSITIVE_FILES.each do |pattern|
        content += "#{pattern}\n"
      end
      
      content += "\n# Build artifacts and dependencies\n"
      content += "node_modules/\n"
      content += "vendor/\n"
      content += "*.log\n"
      content += ".git/\n"
      
      content
    end

    def ensure_volume_exists
      # Check if volume exists
      require "open3"
      stdout, _stderr, status = Open3.capture3("docker", "volume", "ls", "--format", "{{.Name}}")
      volume_list = stdout.split("\n")
      
      if !volume_list.include?(volume_name)
        puts "Creating named volume: #{volume_name}"
        system("docker", "volume", "create", volume_name) || raise("Failed to create volume")
      else
        puts "Using existing volume: #{volume_name}"
      end
    end

    def custom_image_exists?
      require "open3"
      stdout, _stderr, _status = Open3.capture3("docker", "images", "-q", CUSTOM_IMAGE_NAME)
      !stdout.strip.empty?
    end

    def build_custom_image
      return if custom_image_exists?

      puts "\n=== Building custom Docker image ==="
      puts "This may take a few minutes on first run...\n"

      # Generate Dockerfile
      dockerfile_content = DockerfileGenerator.generate(config)
      
      # Create temporary directory for build context
      require "tmpdir"
      Dir.mktmpdir do |tmpdir|
        dockerfile_path = File.join(tmpdir, "Dockerfile")
        File.write(dockerfile_path, dockerfile_content)
        
        puts "Building image with:"
        puts "  - User: #{config.user_name} (#{config.user_id}:#{config.group_id})"
        puts "  - Node.js: installed"
        puts "  - Agents: #{config.selected_agents.empty? ? 'none' : config.selected_agents.join(', ')}"
        puts ""
        
        # Build the image
        success = system("docker", "build", "-t", CUSTOM_IMAGE_NAME, tmpdir)
        
        unless success
          raise "Failed to build custom Docker image"
        end
        
        puts "\n✓ Custom image built successfully: #{CUSTOM_IMAGE_NAME}\n"
      end
    end

    def determine_image(requested_image)
      # If user specified a custom image, use it
      return requested_image unless requested_image == "ubuntu:latest"
      
      # If configured, use custom image
      if config.configured?
        build_custom_image
        CUSTOM_IMAGE_NAME
      else
        requested_image
      end
    end

    def determine_user
      # Return non-root user if configured
      if config.configured?
        "#{config.user_id}:#{config.group_id}"
      else
        nil
      end
    end

    def run_container(image: "ubuntu:latest", command: "/bin/bash", interactive: true)
      create_dockerignore
      ensure_volume_exists
      
      # Determine which image to use
      actual_image = determine_image(image)
      user = determine_user
      
      docker_args = ["docker", "run"]
      docker_args << "--rm"
      docker_args << "-it" if interactive
      docker_args << "--name"
      docker_args << container_name
      
      # Set user if configured
      if user
        docker_args << "--user"
        docker_args << user
      end
      
      docker_args << "-v"
      docker_args << "#{working_dir}:/workspace"
      docker_args << "-w"
      docker_args << "/workspace"
      
      # Check if any agent settings directories exist in the working directory
      has_agent_dirs = AGENT_SETTINGS_DIRS.any? { |dir| File.directory?(File.join(working_dir, dir)) }
      
      if has_agent_dirs
        # Mount the named volume for persistent agent settings
        docker_args << "-v"
        if user
          # Mount to the non-root user's home directory
          docker_args << "#{volume_name}:/home/#{config.user_name}/.agent-settings"
        else
          docker_args << "#{volume_name}:#{AGENT_VOLUME_MOUNT}"
        end
      end
      
      docker_args << actual_image
      
      # Split command if it's a complex command
      if command.include?(" ")
        docker_args << "/bin/sh"
        docker_args << "-c"
        docker_args << command
      else
        docker_args << command
      end
      
      puts "Running: #{docker_args.join(' ')}"
      
      # exec() replaces the current process with the Docker container
      # The process will end when the container stops (--rm removes it automatically)
      exec(*docker_args)
    end
  end
end
